title: Ankita Shukla
description: Machine Learning and Computer Vision
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

author:
  name: Ankita Shukla
  avatar: Ankita_Shukla_Photo.jpg
  bio: "Assistant Professor UNR."

google_analytics: UA-142761361-1

social:
  - name: GitHub
    url: https://github.com/ankitashukla
  - name: LinkedIn
    url: https://www.linkedin.com/in/ankitashukla

markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
