title: Ankita Shukla
description: Machine Learning and Computer Vision
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme

author:
  name: Ankita Shukla
  avatar: /assets/images/Ankita_Shukla_Photo.jpg
  bio: "Assistant Professor focusing on vision language models."
  
